languageCode = 'en-us'
title = 'InfinyOn'

enableRobotsTXT = true
pygmentsUseClasses=true
enableEmoji=true
refLinksErrorLevel = "ERROR"

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "rss"
  [outputFormats.json]
    mediatype = "application/json"
    baseName = "index"
    isPlainText = true

[outputs]
  home = ["html", "rss", "json"]
  page = ["html", "json"]

[params]
  version = "2.0.0"
  short_time_format = "Jan 02, 2006"
  blog_time_format = "January 02, 2006"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true